"""Generate standard-normal expectation rules; runtime needs no Python/SciPy."""
from pathlib import Path
import json
import numpy as np
from scipy.special import roots_hermitenorm

rules = []
for order in [128, 256]:
    nodes, weights = roots_hermitenorm(order)
    rules.append(np.column_stack([nodes, weights / np.sqrt(2 * np.pi)]).tolist())
target = Path(__file__).resolve().parents[1] / "src/core/fit/normalQuadrature.ts"
target.write_text(
    "// Generated by scripts/generate-normal-quadrature.py using SciPy roots_hermitenorm.\n"
    "// Each [node, weight] integrates expectations under N(0, 1).\n"
    "export const normalQuadratureRules = " + json.dumps(rules) + " as const;\n"
)
